"""Generate docs/TOOLS.md and vault/Tool Catalogue.md from the live tool registry."""
from __future__ import annotations

import asyncio
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(ROOT, "src"))

from automaya_mcp.server import TOOL_MODULES, create_app  # noqa: E402


async def build() -> str:
    lines = ["# AutoMaya tool catalogue", "", "Generated by scripts/gen_tool_catalogue.py. Prefix for every tool is `maya_`.", ""]
    total = 0
    for module in TOOL_MODULES:
        app = create_app(modules=[module])
        tools = await app.list_tools()
        tools = [t for t in tools]
        total += len(tools)
        lines.append("## %s (%d)" % (module, len(tools)))
        lines.append("")
        for t in sorted(tools, key=lambda t: t.name):
            desc = (t.description or "").strip().split("\n")[0]
            props = (t.inputSchema or {}).get("properties", {})
            params = props.get("params", {})
            ref = params.get("$ref", "")
            fields = []
            if ref:
                defs = (t.inputSchema or {}).get("$defs", {})
                model = defs.get(ref.split("/")[-1], {})
                fields = list(model.get("properties", {}).keys())
            lines.append("- `%s`: %s%s" % (t.name, desc, (" (params: %s)" % ", ".join(fields)) if fields else ""))
        lines.append("")
    lines.insert(3, "Total tools: %d" % total)
    return "\n".join(lines)


if __name__ == "__main__":
    text = asyncio.run(build())
    for path in ("docs/TOOLS.md", "vault/Tool Catalogue.md"):
        with open(os.path.join(ROOT, path), "w", encoding="utf-8") as fh:
            fh.write(text)
    print(text.split("\n")[3])
